import pathlib, base64

dq = '"'
bt = '`'

lines = []
lines.append('import { useState, useEffect } from ' + dq + 'react' + dq + ';')
lines.append('import { invoke } from ' + dq + '@tauri-apps/api/core' + dq + ';')
lines.append('import type { Player, CeaSettings, CeaMatchInfo, CeaImportPlayer, MatchPlayerInput } from ' + dq + '../types' + dq + ';')
lines.append('')
lines.append('type Step = ' + dq + 'config' + dq + ' | ' + dq + 'syncing' + dq + ' | ' + dq + 'roster' + dq + ' | ' + dq + 'queue' + dq + ' | ' + dq + 'entry' + dq + ' | ' + dq + 'done' + dq + ';')
lines.append('')
lines.append('interface RosterResult {')
lines.append('  entryId: string;')
lines.append('  ceaPlayers: CeaImportPlayer[];')
lines.append('  matchInfos: CeaMatchInfo[];')
lines.append('  error: string | null;')
lines.append('}')
lines.append('')
lines.append('interface QueuedMatch {')
lines.append('  matchId: string;')
lines.append('  date: string | null;')
lines.append('  status: string | null;')
lines.append('  imported: boolean;')
lines.append('  selected: boolean;')
lines.append('}')
lines.append('')
lines.append('const EMPTY_PLAYER = (): MatchPlayerInput => ({')
lines.append('  playerId: null, summonerName: ' + dq + dq + ', champion: ' + dq + dq + ',')
lines.append('  kills: 0, deaths: 0, assists: 0, gold: null,')
lines.append('  won: false, team: 1,')
lines.append('});')
lines.append('')
lines.append('function emptyForm() {')
lines.append('  return {')
lines.append('    duration: ' + dq + dq + ',')
lines.append('    team1Won: true,')
lines.append('    players: [')
lines.append('      ...Array(5).fill(null).map(() => ({ ...EMPTY_PLAYER(), team: 1 as const })),')
lines.append('      ...Array(5).fill(null).map(() => ({ ...EMPTY_PLAYER(), team: 2 as const, won: false })),')
lines.append('    ] as MatchPlayerInput[],')
lines.append('  };')
lines.append('}')
lines.append('')
lines.append('export default function MatchView() {')
lines.append('  const [step, setStep] = useState<Step>(' + dq + 'config' + dq + ');')
lines.append('  const [settings, setSettings] = useState<CeaSettings>({ competitionId: ' + dq + dq + ', entryIds: [] });')
lines.append('  const [entryIdInput, setEntryIdInput] = useState(' + dq + dq + ');')
lines.append('  const [allPlayers, setAllPlayers] = useState<Player[]>([]);')
lines.append('  const [rosterResults, setRosterResults] = useState<RosterResult[]>([]);')
lines.append('  const [rosterIdx, setRosterIdx] = useState(0);')
lines.append('  const [queue, setQueue] = useState<QueuedMatch[]>([]);')
lines.append('  const [queueIdx, setQueueIdx] = useState(0);')
lines.append('  const [form, setForm] = useState(emptyForm());')
lines.append('  const [saving, setSaving] = useState(false);')
lines.append('  const [saveErr, setSaveErr] = useState<string | null>(null);')
lines.append('  const [syncErr, setSyncErr] = useState<string | null>(null);')
lines.append('')
lines.append('  useEffect(() => {')
lines.append('    invoke<CeaSettings>(' + dq + 'get_cea_settings' + dq + ').then(s => setSettings(s)).catch(() => {});')
lines.append('    invoke<Player[]>(' + dq + 'get_all_players' + dq + ').then(setAllPlayers).catch(() => {});')
lines.append('  }, []);')
lines.append('')
lines.append('  function addEntryId() {')
lines.append('    const id = entryIdInput.trim();')
lines.append('    if (!id || settings.entryIds.includes(id)) return;')
lines.append('    const next = { ...settings, entryIds: [...settings.entryIds, id] };')
lines.append('    setSettings(next);')
lines.append('    setEntryIdInput(' + dq + dq + ');')
lines.append('    invoke(' + dq + 'save_cea_settings' + dq + ', { competitionId: next.competitionId, entryIds: next.entryIds }).catch(() => {});')
lines.append('  }')
lines.append('')
lines.append('  function removeEntryId(id: string) {')
lines.append('    const next = { ...settings, entryIds: settings.entryIds.filter(x => x !== id) };')
lines.append('    setSettings(next);')
lines.append('    invoke(' + dq + 'save_cea_settings' + dq + ', { competitionId: next.competitionId, entryIds: next.entryIds }).catch(() => {});')
lines.append('  }')
lines.append('')
lines.append('  async function saveCompId(val: string) {')
lines.append('    const next = { ...settings, competitionId: val };')
lines.append('    setSettings(next);')
lines.append('    await invoke(' + dq + 'save_cea_settings' + dq + ', { competitionId: val, entryIds: next.entryIds }).catch(() => {});')
lines.append('  }')
lines.append('')
lines.append('  async function handleSync() {')
lines.append('    if (!settings.competitionId || settings.entryIds.length === 0) return;')
lines.append('    setStep(' + dq + 'syncing' + dq + ');')
lines.append('    setSyncErr(null);')
lines.append('    try {')
lines.append('      const results: RosterResult[] = await Promise.all(')
lines.append('        settings.entryIds.map(async (entryId) => {')
lines.append('          try {')
lines.append('            const [ceaPlayers, matchInfos] = await Promise.all([')
lines.append('              invoke<CeaImportPlayer[]>(' + dq + 'fetch_cea_roster' + dq + ', { ceaTeamId: parseInt(entryId) }),')
lines.append('              invoke<CeaMatchInfo[]>(' + dq + 'fetch_cea_team_matches' + dq + ', { ceaTeamId: entryId }),')
lines.append('            ]);')
lines.append('            return { entryId, ceaPlayers, matchInfos, error: null };')
lines.append('          } catch (e) {')
lines.append('            return { entryId, ceaPlayers: [], matchInfos: [], error: String(e) };')
lines.append('          }')
lines.append('        })')
lines.append('      );')
lines.append('      setRosterResults(results);')
lines.append('      setRosterIdx(0);')
lines.append('      setStep(' + dq + 'roster' + dq + ');')
lines.append('    } catch (e) {')
lines.append('      setSyncErr(String(e));')
lines.append('      setStep(' + dq + 'config' + dq + ');')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  function handleRosterNext() {')
lines.append('    if (rosterIdx + 1 < rosterResults.length) {')
lines.append('      setRosterIdx(i => i + 1);')
lines.append('    } else {')
lines.append('      const imported = new Set<string>();')
lines.append('      invoke<string[]>(' + dq + 'get_imported_match_ids' + dq + ', { competitionId: settings.competitionId })')
lines.append('        .then(ids => { ids.forEach(id => imported.add(id)); })')
lines.append('        .catch(() => {})')
lines.append('        .finally(() => {')
lines.append('          const seen = new Set<string>();')
lines.append('          const allMatches: QueuedMatch[] = [];')
lines.append('          for (const r of rosterResults) {')
lines.append('            for (const m of r.matchInfos) {')
lines.append('              if (!seen.has(m.matchId)) {')
lines.append('                seen.add(m.matchId);')
lines.append('                allMatches.push({')
lines.append('                  matchId: m.matchId,')
lines.append('                  date: m.date,')
lines.append('                  status: m.status,')
lines.append('                  imported: imported.has(m.matchId),')
lines.append('                  selected: !imported.has(m.matchId),')
lines.append('                });')
lines.append('              }')
lines.append('            }')
lines.append('          }')
lines.append('          setQueue(allMatches.sort((a, b) => (a.date ?? ' + dq + dq + ').localeCompare(b.date ?? ' + dq + dq + ')));')
lines.append('          setStep(' + dq + 'queue' + dq + ');')
lines.append('        });')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  function handleStartEntry() {')
lines.append('    const firstIdx = queue.findIndex(m => m.selected && !m.imported);')
lines.append('    if (firstIdx === -1) { setStep(' + dq + 'done' + dq + '); return; }')
lines.append('    setQueueIdx(firstIdx);')
lines.append('    setForm(emptyForm());')
lines.append('    setSaveErr(null);')
lines.append('    setStep(' + dq + 'entry' + dq + ');')
lines.append('  }')
lines.append('')
lines.append('  const currentMatch = queue[queueIdx] ?? null;')
lines.append('')
lines.append('  function updatePlayer(idx: number, field: keyof MatchPlayerInput, value: unknown) {')
lines.append('    setForm(prev => {')
lines.append('      const players = [...prev.players];')
lines.append('      players[idx] = { ...players[idx], [field]: value };')
lines.append('      if (field !== ' + dq + 'won' + dq + ') {')
lines.append('        players[idx] = { ...players[idx], won: players[idx].team === 1 ? prev.team1Won : !prev.team1Won };')
lines.append('      }')
lines.append('      return { ...prev, players };')
lines.append('    });')
lines.append('  }')
lines.append('')
lines.append('  function setTeam1Won(val: boolean) {')
lines.append('    setForm(prev => ({')
lines.append('      ...prev,')
lines.append('      team1Won: val,')
lines.append('      players: prev.players.map(p => ({ ...p, won: p.team === 1 ? val : !val })),')
lines.append('    }));')
lines.append('  }')
lines.append('')
lines.append('  function resolvePlayerId(name: string): number | null {')
lines.append('    const n = name.toLowerCase().trim();')
lines.append('    const p = allPlayers.find(p =>')
lines.append('      p.summonerName.toLowerCase() === n || p.displayName.toLowerCase() === n')
lines.append('    );')
lines.append('    return p ? p.id : null;')
lines.append('  }')
lines.append('')
lines.append('  function handleSummonerChange(idx: number, val: string) {')
lines.append('    const pid = resolvePlayerId(val);')
lines.append('    setForm(prev => {')
lines.append('      const players = [...prev.players];')
lines.append('      players[idx] = {')
lines.append('        ...players[idx],')
lines.append('        summonerName: val,')
lines.append('        playerId: pid,')
lines.append('        won: players[idx].team === 1 ? prev.team1Won : !prev.team1Won,')
lines.append('      };')
lines.append('      return { ...prev, players };')
lines.append('    });')
lines.append('  }')
lines.append('')
lines.append('  function parseDuration(s: string): number | null {')
lines.append('    s = s.trim();')
lines.append('    if (!s) return null;')
lines.append(r'    const mmsec = s.match(/^(\d+):(\d{2})$/);')
lines.append('    if (mmsec) return parseInt(mmsec[1]) * 60 + parseInt(mmsec[2]);')
lines.append('    const n = parseInt(s);')
lines.append('    return isNaN(n) ? null : n;')
lines.append('  }')
lines.append('')
lines.append('  async function handleSaveMatch() {')
lines.append('    if (!currentMatch) return;')
lines.append('    setSaving(true);')
lines.append('    setSaveErr(null);')
lines.append('    try {')
lines.append('      const filledPlayers = form.players.filter(p => p.summonerName.trim() !== ' + dq + dq + ');')
lines.append('      await invoke(' + dq + 'save_match' + dq + ', {')
lines.append('        competitionId: settings.competitionId,')
lines.append('        ceaMatchId: currentMatch.matchId,')
lines.append('        durationSec: parseDuration(form.duration),')
lines.append('        playedAt: currentMatch.date ?? null,')
lines.append('        players: filledPlayers.map(p => ({ ...p, playerId: resolvePlayerId(p.summonerName) })),')
lines.append('      });')
lines.append('      setQueue(prev => prev.map((m, i) =>')
lines.append('        i === queueIdx ? { ...m, imported: true, selected: false } : m')
lines.append('      ));')
lines.append('      const nextIdx = queue.findIndex((m, i) => i > queueIdx && m.selected && !m.imported);')
lines.append('      if (nextIdx === -1) {')
lines.append('        setStep(' + dq + 'done' + dq + ');')
lines.append('      } else {')
lines.append('        setQueueIdx(nextIdx);')
lines.append('        setForm(emptyForm());')
lines.append('        setSaveErr(null);')
lines.append('      }')
lines.append('    } catch (e) {')
lines.append('      setSaveErr(String(e));')
lines.append('    } finally {')
lines.append('      setSaving(false);')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  function handleSkipMatch() {')
lines.append('    const nextIdx = queue.findIndex((m, i) => i > queueIdx && m.selected && !m.imported);')
lines.append('    if (nextIdx === -1) { setStep(' + dq + 'done' + dq + '); return; }')
lines.append('    setQueueIdx(nextIdx);')
lines.append('    setForm(emptyForm());')
lines.append('    setSaveErr(null);')
lines.append('  }')
lines.append('')
lines.append('  const selectedCount = queue.filter(m => m.selected && !m.imported).length;')
lines.append('')
lines.append('  if (step === ' + dq + 'config' + dq + ' || step === ' + dq + 'syncing' + dq + ') {')
lines.append('    return (')
lines.append('      <div className=' + dq + 'match-layout' + dq + '>')
lines.append('        <div className=' + dq + 'match-header' + dq + '>')
lines.append('          <h2 className=' + dq + 'match-title' + dq + '>Match Sync</h2>')
lines.append('          <p className=' + dq + 'match-subtitle' + dq + '>Pull rosters and match list from CEA, then enter match results.</p>')
lines.append('        </div>')
lines.append('        <div className=' + dq + 'match-config-section' + dq + '>')
lines.append('          <label className=' + dq + 'match-config-label' + dq + '>Competition ID</label>')
lines.append('          <input className=' + dq + 'match-config-input' + dq + ' placeholder=' + dq + 'e.g. 2595' + dq + ' value={settings.competitionId} onChange={e => saveCompId(e.target.value)} />')
lines.append('        </div>')
lines.append('        <div className=' + dq + 'match-config-section' + dq + '>')
lines.append('          <label className=' + dq + 'match-config-label' + dq + '>Team Entry IDs</label>')
lines.append('          <div className=' + dq + 'match-entry-id-row' + dq + '>')
lines.append('            <input className=' + dq + 'match-config-input' + dq + ' placeholder=' + dq + 'e.g. 43175' + dq + ' value={entryIdInput} onChange={e => setEntryIdInput(e.target.value)} onKeyDown={e => e.key === ' + dq + 'Enter' + dq + ' && addEntryId()} />')
lines.append('            <button onClick={addEntryId} disabled={!entryIdInput.trim()}>Add</button>')
lines.append('          </div>')
lines.append('          {settings.entryIds.length > 0 && (')
lines.append('            <div className=' + dq + 'match-entry-id-list' + dq + '>')
lines.append('              {settings.entryIds.map(id => (')
lines.append('                <span key={id} className=' + dq + 'match-entry-id-tag' + dq + '>{id}<button className=' + dq + 'match-entry-id-remove' + dq + ' onClick={() => removeEntryId(id)}>x</button></span>')
lines.append('              ))}')
lines.append('            </div>')
lines.append('          )}')
lines.append('        </div>')
lines.append('        {syncErr && <code className=' + dq + 'rank-error-text' + dq + '>{syncErr}</code>}')
lines.append('        <div>')
lines.append('          <button onClick={handleSync} disabled={!settings.competitionId || settings.entryIds.length === 0 || step === ' + dq + 'syncing' + dq + '}>')
lines.append('            {step === ' + dq + 'syncing' + dq + ' ? ' + dq + 'Syncing...' + dq + ' : `Sync (${settings.entryIds.length} team${settings.entryIds.length !== 1 ? ' + dq + 's' + dq + ' : ' + dq + dq + '})`}')
lines.append('          </button>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    );')
lines.append('  }')
lines.append('')
lines.append('  if (step === ' + dq + 'roster' + dq + ') {')
lines.append('    const r = rosterResults[rosterIdx];')
lines.append('    return (')
lines.append('      <div className=' + dq + 'match-layout' + dq + '>')
lines.append('        <div className=' + dq + 'match-step-header' + dq + '><span className=' + dq + 'match-step-badge' + dq + '>Step 2 of 3 - Roster</span><span className=' + dq + 'match-step-progress' + dq + '>{rosterIdx + 1} / {rosterResults.length}</span></div>')
lines.append('        <div className=' + dq + 'match-header' + dq + '><h2 className=' + dq + 'match-title' + dq + '>Roster: Entry {r.entryId}</h2><p className=' + dq + 'match-subtitle' + dq + '>Verify CEA roster matches your DB.</p></div>')
lines.append('        {r.error && <code className=' + dq + 'rank-error-text' + dq + '>{r.error}</code>}')
lines.append('        <div className=' + dq + 'match-roster-grid' + dq + '>')
lines.append('          <div className=' + dq + 'match-roster-col' + dq + '>')
lines.append('            <div className=' + dq + 'match-roster-col-header' + dq + '>CEA Roster ({r.ceaPlayers.length})</div>')
lines.append('            {r.ceaPlayers.map((p, i) => {')
lines.append('              const inDb = allPlayers.some(dp => dp.summonerName.toLowerCase() === p.name.toLowerCase() || dp.displayName.toLowerCase() === p.name.toLowerCase());')
lines.append('              return (')
lines.append('                <div key={i} className={`match-roster-row ${inDb ? ' + dq + 'match-roster-ok' + dq + ' : ' + dq + 'match-roster-missing' + dq + '}`}>')
lines.append('                  <span>{p.name}</span><span className=' + dq + 'muted' + dq + '>{p.isStarter ? ' + dq + 'Starter' + dq + ' : ' + dq + 'Sub' + dq + '}</span>')
lines.append('                  {!inDb && <span className=' + dq + 'match-roster-warn' + dq + '>not in DB</span>}')
lines.append('                </div>')
lines.append('              );')
lines.append('            })}')
lines.append('          </div>')
lines.append('          <div className=' + dq + 'match-roster-col' + dq + '>')
lines.append('            <div className=' + dq + 'match-roster-col-header' + dq + '>Matches found: {r.matchInfos.length}</div>')
lines.append('            {r.matchInfos.slice(0, 8).map((m, i) => (<div key={i} className=' + dq + 'match-roster-row muted' + dq + '>#{m.matchId}{m.date ? ` - ${m.date.slice(0, 10)}` : ' + dq + dq + '}{m.status ? ` [${m.status}]` : ' + dq + dq + '}</div>))}')
lines.append('            {r.matchInfos.length > 8 && <div className=' + dq + 'muted' + dq + '>...and {r.matchInfos.length - 8} more</div>}')
lines.append('            {r.matchInfos.length === 0 && !r.error && <div className=' + dq + 'muted' + dq + '>No matches returned</div>}')
lines.append('          </div>')
lines.append('        </div>')
lines.append('        <div className=' + dq + 'match-step-actions' + dq + '>')
lines.append('          <button onClick={() => setStep(' + dq + 'config' + dq + ')} className=' + dq + 'btn-secondary' + dq + '>Back</button>')
lines.append('          <button onClick={handleRosterNext}>{rosterIdx + 1 < rosterResults.length ? ' + dq + 'Next Team' + dq + ' : ' + dq + 'Build Match Queue' + dq + '}</button>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    );')
lines.append('  }')
lines.append('')
lines.append('  if (step === ' + dq + 'queue' + dq + ') {')
lines.append('    return (')
lines.append('      <div className=' + dq + 'match-layout' + dq + '>')
lines.append('        <div className=' + dq + 'match-step-header' + dq + '><span className=' + dq + 'match-step-badge' + dq + '>Step 3 of 3 - Match Queue</span></div>')
lines.append('        <div className=' + dq + 'match-header' + dq + '>')
lines.append('          <h2 className=' + dq + 'match-title' + dq + '>Match Queue</h2>')
lines.append('          <p className=' + dq + 'match-subtitle' + dq + '>{queue.length} unique match{queue.length !== 1 ? ' + dq + 'es' + dq + ' : ' + dq + dq + '} found. {queue.filter(m => m.imported).length} already imported.{queue.length === 0 && ' + dq + ' Add match IDs below.' + dq + '}</p>')
lines.append('        </div>')
lines.append('        {queue.length > 0 && (')
lines.append('          <table className=' + dq + 'match-table match-queue-table' + dq + '>')
lines.append('            <thead><tr><th style={{ width: 32 }}></th><th>Match ID</th><th>Date</th><th>Status</th><th>State</th></tr></thead>')
lines.append('            <tbody>')
lines.append('              {queue.map((m, i) => (')
lines.append('                <tr key={m.matchId} className={m.imported ? ' + dq + 'match-row-done' + dq + ' : ' + dq + dq + '}>')
lines.append('                  <td><input type=' + dq + 'checkbox' + dq + ' checked={m.selected} disabled={m.imported} onChange={e => setQueue(prev => prev.map((q, j) => j === i ? { ...q, selected: e.target.checked } : q))} /></td>')
lines.append('                  <td className=' + dq + 'match-ocr-name' + dq + '>{m.matchId}</td>')
lines.append('                  <td className=' + dq + 'muted' + dq + '>{m.date?.slice(0, 10) ?? ' + dq + '--' + dq + '}</td>')
lines.append('                  <td className=' + dq + 'muted' + dq + '>{m.status ?? ' + dq + '--' + dq + '}</td>')
lines.append('                  <td>{m.imported ? <span className=' + dq + 'match-saved' + dq + '>done</span> : <span className=' + dq + 'muted' + dq + '>pending</span>}</td>')
lines.append('                </tr>')
lines.append('              ))}')
lines.append('            </tbody>')
lines.append('          </table>')
lines.append('        )}')
lines.append('        <ManualMatchAdd competitionId={settings.competitionId} onAdd={(matchId) => { if (queue.some(m => m.matchId === matchId)) return; setQueue(prev => [...prev, { matchId, date: null, status: null, imported: false, selected: true }]); }} />')
lines.append('        <div className=' + dq + 'match-step-actions' + dq + '>')
lines.append('          <button onClick={() => setStep(' + dq + 'roster' + dq + ')} className=' + dq + 'btn-secondary' + dq + '>Back</button>')
lines.append('          <button onClick={handleStartEntry} disabled={selectedCount === 0}>Enter Data ({selectedCount} match{selectedCount !== 1 ? ' + dq + 'es' + dq + ' : ' + dq + dq + '})</button>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    );')
lines.append('  }')
lines.append('')
lines.append('  if (step === ' + dq + 'entry' + dq + ' && currentMatch) {')
lines.append('    const matchUrl = `https://app.playcea.com/competition/${settings.competitionId}/match/${currentMatch.matchId}`;')
lines.append('    const selectedMatches = queue.filter(m => m.selected && !m.imported);')
lines.append('    const currentPos = selectedMatches.findIndex(m => m.matchId === currentMatch.matchId) + 1;')
lines.append('    return (')
lines.append('      <div className=' + dq + 'match-entry-layout' + dq + '>')
lines.append('        <div className=' + dq + 'match-entry-iframe-panel' + dq + '>')
lines.append('          <div className=' + dq + 'match-entry-iframe-header' + dq + '>')
lines.append('            <span className=' + dq + 'match-step-badge' + dq + '>Match {currentPos} of {selectedMatches.length}</span>')
lines.append('            <a href={matchUrl} target=' + dq + '_blank' + dq + ' rel=' + dq + 'noreferrer' + dq + ' className=' + dq + 'match-entry-open-link' + dq + '>open</a>')
lines.append('          </div>')
lines.append('          <iframe src={matchUrl} className=' + dq + 'match-entry-iframe' + dq + ' title={`Match ${currentMatch.matchId}`} />')
lines.append('        </div>')
lines.append('        <div className=' + dq + 'match-entry-form-panel' + dq + '>')
lines.append('          <div className=' + dq + 'match-entry-form-scroll' + dq + '>')
lines.append('            <span className=' + dq + 'match-title' + dq + '>Match #{currentMatch.matchId}</span>')
lines.append('            <div className=' + dq + 'match-form-row' + dq + '>')
lines.append('              <label className=' + dq + 'match-form-label' + dq + '>Duration (MM:SS)</label>')
lines.append('              <input className=' + dq + 'match-form-input-sm' + dq + ' placeholder=' + dq + 'e.g. 32:15' + dq + ' value={form.duration} onChange={e => setForm(prev => ({ ...prev, duration: e.target.value }))} />')
lines.append('            </div>')
lines.append('            <div className=' + dq + 'match-winner-row' + dq + '>')
lines.append('              <span className=' + dq + 'match-winner-label' + dq + '>Winner:</span>')
lines.append('              <label className={`match-winner-btn ${form.team1Won ? ' + dq + 'active' + dq + ' : ' + dq + dq + '}`}><input type=' + dq + 'radio' + dq + ' name=' + dq + 'winner' + dq + ' checked={form.team1Won} onChange={() => setTeam1Won(true)} />Team 1</label>')
lines.append('              <label className={`match-winner-btn ${!form.team1Won ? ' + dq + 'active' + dq + ' : ' + dq + dq + '}`}><input type=' + dq + 'radio' + dq + ' name=' + dq + 'winner' + dq + ' checked={!form.team1Won} onChange={() => setTeam1Won(false)} />Team 2</label>')
lines.append('            </div>')
lines.append('            {([1, 2] as const).map(team => (')
lines.append('              <div key={team} className=' + dq + 'match-team-section' + dq + '>')
lines.append('                <div className={`match-team-header ${(team === 1) === form.team1Won ? ' + dq + 'match-team-win' + dq + ' : ' + dq + 'match-team-loss' + dq + '}`}>Team {team} - {(team === 1) === form.team1Won ? ' + dq + 'Victory' + dq + ' : ' + dq + 'Defeat' + dq + '}</div>')
lines.append('                <table className=' + dq + 'match-table match-entry-table' + dq + '>')
lines.append('                  <thead><tr><th>Summoner</th><th>Champion</th><th>K</th><th>D</th><th>A</th><th>Gold</th></tr></thead>')
lines.append('                  <tbody>')
lines.append('                    {form.players.map((p, i) => ({ p, i })).filter(({ p }) => p.team === team).map(({ p, i }) => (')
lines.append('                      <tr key={i}>')
lines.append('                        <td><input list=' + dq + 'summoner-list' + dq + ' className=' + dq + 'match-form-input' + dq + ' placeholder=' + dq + 'Summoner name' + dq + ' value={p.summonerName} onChange={e => handleSummonerChange(i, e.target.value)} /></td>')
lines.append('                        <td><input className=' + dq + 'match-form-input' + dq + ' placeholder=' + dq + 'Champion' + dq + ' value={p.champion} onChange={e => updatePlayer(i, ' + dq + 'champion' + dq + ', e.target.value)} /></td>')
lines.append('                        {([' + dq + 'kills' + dq + ', ' + dq + 'deaths' + dq + ', ' + dq + 'assists' + dq + '] as const).map(f => (<td key={f}><input type=' + dq + 'number' + dq + ' min=' + dq + '0' + dq + ' max=' + dq + '99' + dq + ' className=' + dq + 'match-form-input-num' + dq + ' value={p[f]} onChange={e => updatePlayer(i, f, parseInt(e.target.value) || 0)} /></td>))}')
lines.append('                        <td><input type=' + dq + 'number' + dq + ' min=' + dq + '0' + dq + ' className=' + dq + 'match-form-input-num match-form-input-gold' + dq + ' placeholder=' + dq + '--' + dq + ' value={p.gold ?? ' + dq + dq + '} onChange={e => updatePlayer(i, ' + dq + 'gold' + dq + ', e.target.value === ' + dq + dq + ' ? null : parseInt(e.target.value) || 0)} /></td>')
lines.append('                      </tr>')
lines.append('                    ))}')
lines.append('                  </tbody>')
lines.append('                </table>')
lines.append('              </div>')
lines.append('            ))}')
lines.append('            {saveErr && <code className=' + dq + 'rank-error-text' + dq + '>{saveErr}</code>}')
lines.append('            <div className=' + dq + 'match-save-row' + dq + '>')
lines.append('              <button onClick={handleSaveMatch} disabled={saving}>{saving ? ' + dq + 'Saving...' + dq + ' : ' + dq + 'Save & Next' + dq + '}</button>')
lines.append('              <button className=' + dq + 'btn-secondary' + dq + ' onClick={handleSkipMatch} disabled={saving}>Skip</button>')
lines.append('              <button className=' + dq + 'btn-secondary' + dq + ' onClick={() => setStep(' + dq + 'queue' + dq + ')} disabled={saving}>Queue</button>')
lines.append('            </div>')
lines.append('          </div>')
lines.append('        </div>')
lines.append('        <datalist id=' + dq + 'summoner-list' + dq + '>{allPlayers.map(p => (<option key={p.id} value={p.summonerName}>{p.displayName}</option>))}</datalist>')
lines.append('      </div>')
lines.append('    );')
lines.append('  }')
lines.append('')
lines.append('  return (')
lines.append('    <div className=' + dq + 'match-layout' + dq + '>')
lines.append('      <div className=' + dq + 'match-header' + dq + '>')
lines.append('        <h2 className=' + dq + 'match-title' + dq + '>All Done</h2>')
lines.append('        <p className=' + dq + 'match-subtitle' + dq + '>{queue.filter(m => m.imported).length} match{queue.filter(m => m.imported).length !== 1 ? ' + dq + 'es' + dq + ' : ' + dq + dq + '} imported. Player stats have been updated.</p>')
lines.append('      </div>')
lines.append('      <div className=' + dq + 'match-step-actions' + dq + '>')
lines.append('        <button onClick={() => { setStep(' + dq + 'config' + dq + '); setQueue([]); }}>Start Over</button>')
lines.append('        <button className=' + dq + 'btn-secondary' + dq + ' onClick={() => setStep(' + dq + 'queue' + dq + ')}>Back to Queue</button>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  );')
lines.append('}')
lines.append('')
lines.append('function ManualMatchAdd({ competitionId: _competitionId, onAdd }: { competitionId: string; onAdd: (id: string) => void }) {')
lines.append('  const [val, setVal] = useState(' + dq + dq + ');')
lines.append('  return (')
lines.append('    <div className=' + dq + 'match-manual-add' + dq + '>')
lines.append('      <span className=' + dq + 'match-config-label' + dq + '>Add match ID manually:</span>')
lines.append('      <div className=' + dq + 'match-entry-id-row' + dq + '>')
lines.append('        <input className=' + dq + 'match-config-input' + dq + ' placeholder=' + dq + 'e.g. 74529' + dq + ' value={val} onChange={e => setVal(e.target.value)} onKeyDown={e => { if (e.key === ' + dq + 'Enter' + dq + ') { onAdd(val.trim()); setVal(' + dq + dq + '); } }} />')
lines.append('        <button onClick={() => { onAdd(val.trim()); setVal(' + dq + dq + '); }} disabled={!val.trim()}>Add</button>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  );')
lines.append('}')

tsx = '\n'.join(lines)
b64 = base64.b64encode(tsx.encode('utf-8')).decode()
pathlib.Path('C:/Users/Holms/repos/cea-lol-broadcast/_match_b64.txt').write_text(b64)
print('b64 written, tsx len:', len(tsx))
